name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up SSH key
      env:
        SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER: ${{ secrets.SERVER_IP }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H "$SERVER" >> ~/.ssh/known_hosts