name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up SSH key
      env:
        SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        SERVER: ${{ secrets.SERVER_IP }}
        PORT: ${{ secrets.SSH_PORT }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -p "$PORT" -H "$SERVER" >> ~/.ssh/known_hosts

    - name: Update repository
      env:
        SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        SERVER: ${{ secrets.SERVER_IP }}
        PORT: ${{ secrets.SSH_PORT }}
        CICD_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -i ~/.ssh/id_ed25519 -p "$PORT" -o StrictHostKeyChecking=yes "$CICD_USER"@"$SERVER"