name: Deploy to server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up SSH key
      env:
        SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        SERVER: ${{ secrets.ORIGIN }}
        PORT: ${{ secrets.SSH_PORT }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519
        echo "Adding $SERVER:$PORT to known_hosts..."
        ssh-keyscan -p "$PORT" -H "$SERVER" >> ~/.ssh/known_hosts

    - name: Clone repository
      env:
        SERVER: ${{ secrets.ORIGIN }}
        PORT: ${{ secrets.SSH_PORT }}
        USER: ${{ secrets.USER }}
      run: |
        ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 -p "$PORT" "$USER@$SERVER" '
          set -e
          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls -la ~

          if [ -f docker-compose.yml ]; then
            docker-compose down
          fi

          if [ ! -d "$APP_DIR/.git" ]; then
            git init
            git remote add origin git@github.com:FrankenBunny/chameleon_game.git
          fi

          git fetch origin
          git reset --hard origin/main

          if [ -f docker-compose.yml ]; then
            docker-compose up -d --build
          fi

          echo "Deployment finished successfully."
        '
